### ISSUE TITLE
lazy_static without unsafe?

### ISSUE THREAD

**Issue by matthiasbeyer** [rust-lang-nursery/lazy-static.rs#125]
Hi,

I'm trying to use `#![forbid(unsafe_code)]` but I also want to use `lazy_static!()` - is there a way?

My failling travis job is [here](https://travis-ci.org/matthiasbeyer/imag/jobs/433965678#L941)

**Comment by KodrAus** [comment]
Hmm, the problem here is that the macro-generated `deref` impl for lazy statics [uses an `unsafe` block](https://github.com/rust-lang-nursery/lazy-static.rs/blob/master/src/lib.rs#L142-L152) because it accesses a `'static mut`. In #124 we're removing the need for `'static mut`, so we should be able to work properly with crates that `#![forbid(unsafe_code)]`.

**Comment by KodrAus** [comment]
Alrighty! It should be possible now to use `lazy_static` `1.2.0` alongside `#![forbid(unsafe_code)]`.
