### ISSUE TITLE
Require all lazy statics to have a starting/default value and only allow 1 initialization at a time

### ISSUE THREAD

**Issue by SoniEx2** [rust-lang-nursery/lazy-static.rs#43]
See #37

**Comment by Kimundi** [comment]
I'm not sure if this is a good idea, as it would complicate the somewhat straightforward semantic lazy statics have right now, and might have performance implications.

**Comment by SoniEx2** [comment]
Maybe requiring them is a bad idea, but the option would be nice.

**Comment by briansmith** [comment]
@SoniEx2 Your proposed semantics don't match the mental model of `lazy_static!`. The whole idea of `lazy_static!` is that the "initial value" is computed. Having a different initial value is somewhat counter to that.

**Comment by SoniEx2** [comment]
@briansmith Well uh... How else do you propose we handle cyclic references?

**Comment by Kimundi** [comment]
Hi, I'm [sincerely sorry for taking so long to respond.](https://gist.github.com/Kimundi/9b10629d29adbf163d8eb053ddaa1f38)

I'm making the the decision now that I do not want to complicate lazy_static by supporting pre-initialization values.

However, I'm open for alternative solutions like accessors to check the initialization state so that code can avoid a cycle externally by using a different source for the initial value.
