### ISSUE TITLE
How to mutate lazy-static at runtime

### ISSUE THREAD

**Issue by lobachevzky** [rust-lang-nursery/lazy-static.rs#56]
I am trying to use lazy-static to implement a global object pool. The idea is that when objects of a certain kind get dropped, they are put in the pool instead of having their memory freed. Subsequently, instead of immediately allocating memory for these objects, we can first check if there are is an object available in the pool.

The problem is that whenever I try to perform certain kinds of mutation to the pool, the program hangs at what appears to be a mutex deadlock.

Here is the code for the pool
```rust
lazy_static! {
    static ref POOL: Mutex<HashMap<(u32, u32), Vec<PMatrix>>> = 
        Mutex::new(HashMap::new()); // keys represent dimensions of matrices
}
```
And here is the function that is hanging:
```rust
impl PMatrix {
    pub fn empty(height: u32, width: u32) -> PMatrix {
        POOL.lock().unwrap()
            .entry((height, width))
            .or_insert(vec![PMatrix::from(Matrix::empty(height, width))]) // this is where the code seems to hang
            .pop().unwrap()
    }
}
```
Strangely, the following code does not seem to cause any problems:

```rust
impl Drop for PMatrix {
    fn drop(&mut self) {
        if let Some(matrix) = self.matrix.take() {
            let mut pool = POOL.lock().unwrap();
            let mut matrices = pool.entry((matrix.height, matrix.width))
                                   .or_insert(vec![]);
            matrices.push(PMatrix::from(matrix));
        }
    }
}
```

Thank you for your help. Please let me know if there is a better way to go about doing this.

**Comment by Kimundi** [comment]
Hi, I'm [sincerely sorry for taking so long to respond.](https://gist.github.com/Kimundi/9b10629d29adbf163d8eb053ddaa1f38)

Just based on the code posted here I'm not sure what is causing it - it might be that the
`PMatrix::from()` and/or `Matrix::empty()` calls might end up accessing `POOL` as well, causing a cycle in the initialization code.

I'm not sure how to best address this. One possible solution would be to have `empty()` lock and unlock the hashmap multiple times to be able to call that offending line without a lock being in the way, but that might not be what you want due to performance and different behaviour with concurrent accesses to the hashmap.

Another solution might be to explicitly pass the `POOL` lock's reference around through the method calls, or as a hidden field of `PMatrix` (Or have a wrapper around PMatrix that does that for the sake of doing modification and access chains like this in a single locked operation).

**Comment by lobachevzky** [comment]
I believe that the issue was addressed in [this stackoverflow post](http://stackoverflow.com/questions/41323505/why-isnt-mutex-unlocking). Take a look and if that's not it, we can take a second look.

**Comment by Kimundi** [comment]
Well, the question is if the issue is resolved for you now. :)

**Comment by lobachevzky** [comment]
I guess that the issue was outside lazy-static. I had to read over the post a second time.
