### ISSUE TITLE
lazy-static doesn't work with rust-stable 1.15.0

### ISSUE THREAD

**Issue by daym** [rust-lang-nursery/lazy-static.rs#59]
lazy-static checks for the `nightly` feature and only then uses `std::sync::Once`.

However, `std::sync::Once` is part of rust proper since 1.14.0. Could the check be amended to take this fact into account?

**Comment by Kimundi** [comment]
Hm, I'm not sure what you are referring to - lazy_static uses `std::sync::Once` both on stable and on its both nightly features. The only difference is wether its const-fn constructor is used or not.

Looking at the linked issue, it seems the actual problem is the attempt to use the `spin_no_std` feature on stable.

**Comment by daym** [comment]
There seem to be these cases:

```#[cfg(all(feature="nightly", not(feature="spin_no_std")))] ...
#[path="nightly_lazy.rs"]```

and

```#[cfg(all(feature="nightly", feature="spin_no_std"))]
#[path="core_lazy.rs"]```

We are trying to package rust stable in the GNU Guix distribution which is right now blocked on `lazy_static` because we can't see how this is supposed to work at all on Rust stable.

**Comment by Kimundi** [comment]
Hm, I'm still a bit confused.

Lazy static works on stable rust (aka the stable release of the compiler) out of the box - the two `#[cfg]` lines you pasted are alternative implementations of this crate, which both only work with the nightly compiler and need to be explicitly enabled.

If I understand it right the issue might be that you are trying to compile a dependency tree with cargo where some crate in there is not compatible with stable Rust and pull in lazy_static with the nighlty feature enabled.

Because cargo tries to unify different versions of the same crates inside its dependecy tree, this might cause it to always enable the nightly feature - which makes the crate not compile because you are on stable, and might not point at the crate that is actually causing this.

**Comment by daym** [comment]
>Lazy static works on stable rust (aka the stable release of the compiler) out of the box

Maybe I'm confused. But we don't patch packages that work well. lazy_static 0.2.4 does break (using cargo build) using Rust static:

I've just removed all custom patches and then I get:

```
error: no matching package named `spin` found (required by `lazy_static`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: ^0.4
phase `build' failed after 0.1 seconds
```

**Comment by Kimundi** [comment]
Short answer: Without additional input to cargo, the `#[cfg(not(feature="nightly"))]` should be picked because cargo should not consider the `nightly` or `spin_no_std` features to be enabled, which should also lead to it not trying to compile the optional `spin` dependency.

As far as I know, if it does so anyway, then the issue is somehow on your end. Potentially cause by other crates that depend on lazy_static that you also try to compile at the same time.

---
Going more in detail what should happen (and does happen, I just tested it on my end):

The `Cargo.toml` has these lines:

```
[dependencies.spin]
version = "0.4"
optional = true

[features]
nightly = []
spin_no_std = ["nightly", "spin"]
```

Lets assume a crate depends on lazy static like this:

```
[dependencies.lazy_static]
version = "0.2"
```

The doing a `cargo build` of that crate should have the following effects:

- cargo sees that the dependency on lazy_static does not require any features to be enabled.
- cargo sees that lazy_static has a optional dependency on the `spin` crate.
- cargo sees that lazy_static does not have any default features defined.
- cargo sees that lazy_static does have the optional feature `nightly`
- cargo sees that lazy_static does have the optional feature `spin_no_std`, which implies the flag `nightly` being enabled and implies a dependency on the `spin` crate.
- cargo now knows that for this crate lazy_static does not need to be compiled with any feature flag activated.
- cargo starts compiling the dependencies of lazy_static.
- cargo knows that the dependency `spin` is optional, and no feature depending on it is enabled, so it does not compile `spin`.
- cargo starts compiling lazy_static.

On its inside, these three items are then of particular interest:
```rust
#[cfg(not(feature="nightly"))]
pub mod lazy; // implies #[path="lazy.rs"]

#[cfg(all(feature="nightly", not(feature="spin_no_std")))]
#[path="nightly_lazy.rs"]
pub mod lazy;

#[cfg(all(feature="nightly", feature="spin_no_std"))]
#[path="core_lazy.rs"]
pub mod lazy;
```
Because no feature is enabled, the `nightly` is not enabled, which means the first `lazy` module gets compiled in, and the other two discarded.

Only if I explicitly force the test crate to depend on the `spin_no_std` feature do I get a error on stable:

```
[dependencies.lazy_static]
version = "0.2"
features = ["spin_no_std"]
```

```
> rustup run stable cargo build
   Compiling spin v0.4.5
error[E0554]: #[feature] may not be used on the stable release channel
 --> /home/marvin/.cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.4.5/src/lib.rs:6:30
  |
6 | #![cfg_attr(feature = "asm", feature(asm))]
  |                              ^^^^^^^^^^^^

error[E0554]: #[feature] may not be used on the stable release channel
 --> /home/marvin/.cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.4.5/src/lib.rs:7:42
  |
7 | #![cfg_attr(feature = "core_intrinsics", feature(core_intrinsics))]
  |                                          ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #[feature] may not be used on the stable release channel
 --> /home/marvin/.cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.4.5/src/lib.rs:8:35
  |
8 | #![cfg_attr(feature = "const_fn", feature(const_fn))]
  |                                   ^^^^^^^^^^^^^^^^^

error: aborting due to 3 previous errors

error: Could not compile `spin`.

To learn more, run the command again with --verbose.
```

**Comment by daym** [comment]
Thanks for the explanation!

```
pub mod lazy; // implies #[path="lazy.rs"]
```

Ahh! Thanks, I didn't know that.

I tried around some more, doing the following substitution makes it work fine:

```
             (substitute* "Cargo.toml"
               (("^[[]dependencies[.]spin[]]") "")
               (("^version = \"0.4\"") "") ; spin
               (("^optional = true") "") ; spin
               (("^spin_no_std.*") "
"))))
```

**Comment by daym** [comment]
Apparently so. Providing a dummy spin makes it work. Huh.

**Comment by Kimundi** [comment]
I don't know what cargo tires to do internally, but at least going by my console output it does not attempt to compile `spin` if it does not need it.
